### ISSUE TITLE
babel-eslint as dependency

### ISSUE THREAD

**Issue by Sinewyk** [lrqdo/styleguide#4]
related to #1  ... is it still necessary ? if it is, we should add it to dependencies, if it's not we should remove default parser https://github.com/lrqdo/styleguide/blob/master/javascript/linters/.eslintrc#L2

**Comment by rik** [comment]
No it is not :) Removed in https://github.com/lrqdo/styleguide/commit/52a04728bd99fecd8ed3401787233d73e96943eb
